#!/bin/bash

# Run the "gradeCompiler" function of the grading harness from the current dir.
# USAGE: ../gradecompiler ARGS...
#               (where 'make' is run from the current directory)
#    OR: ./gradecompiler -dir DIR ARGS...
#               (where 'make' is run from the argument DIR to '-dir'.)
# The additional arguments ARGS... are passed to gradeCompiler to parse.

script_directory=$(dirname "$(python3 -c "import os; print(os.path.realpath('$0'))")")

# If the first two arguments are "-dir <directory>", change the working
# directory to be the given directory.
# Mostly intended to be used by autograder
if [ "$1" = "-dir" ]; then
   cd "$2" || exit
   shift
   shift
fi

"$script_directory/harness/runHarness" gradeCompiler "$@"
